require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/credit_cards", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CreditCard. As you add validations to CreditCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CreditCard.create! valid_attributes
      get credit_cards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      credit_card = CreditCard.create! valid_attributes
      get credit_card_url(credit_card)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_credit_card_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      credit_card = CreditCard.create! valid_attributes
      get edit_credit_card_url(credit_card)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CreditCard" do
        expect {
          post credit_cards_url, params: { credit_card: valid_attributes }
        }.to change(CreditCard, :count).by(1)
      end

      it "redirects to the created credit_card" do
        post credit_cards_url, params: { credit_card: valid_attributes }
        expect(response).to redirect_to(credit_card_url(CreditCard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CreditCard" do
        expect {
          post credit_cards_url, params: { credit_card: invalid_attributes }
        }.to change(CreditCard, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post credit_cards_url, params: { credit_card: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested credit_card" do
        credit_card = CreditCard.create! valid_attributes
        patch credit_card_url(credit_card), params: { credit_card: new_attributes }
        credit_card.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the credit_card" do
        credit_card = CreditCard.create! valid_attributes
        patch credit_card_url(credit_card), params: { credit_card: new_attributes }
        credit_card.reload
        expect(response).to redirect_to(credit_card_url(credit_card))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        credit_card = CreditCard.create! valid_attributes
        patch credit_card_url(credit_card), params: { credit_card: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested credit_card" do
      credit_card = CreditCard.create! valid_attributes
      expect {
        delete credit_card_url(credit_card)
      }.to change(CreditCard, :count).by(-1)
    end

    it "redirects to the credit_cards list" do
      credit_card = CreditCard.create! valid_attributes
      delete credit_card_url(credit_card)
      expect(response).to redirect_to(credit_cards_url)
    end
  end
end
